language: java
jdk:
  - oraclejdk8
deploy:
  provider: heroku
  app: miniaccounting-api
  api_key:
    secure: wEDKA7/JKgCneac0GHnUscVjyYJcrV1/p81S3i5ntbi58udb3qxYeHuDVxR+9fXq7FIjTqEyeQrQz0LX4oM6lhIlqRMO99YL6DW8Q2I1hGZgGtO1GB8QsthidOq9/SR4dUNtKIxhC5TrY9s8yg7cQEZn44Uhq9z3YOAzgWD3mdOCtZKZwX9uEGgnfWbQLWtdRUGnGPswIuD9ePlje2D9GRhjVNL6z0+yTucD0FxsDKK1BEkVVy9Pk+BwWYtJ+rgNFTrMD1p4jnJuO0eDCADrasppcZjZTvX+xA7R7nBDwp0ysGQqjq3W7iD3EMDkV2TNjNKslev+usoIFhOiaffj5YrqP63isC9BSlGkwSJ3S2A23JvgQUcK/N9u4vTAWaxYE/ZvujqjIR8Z/E/+JkjlkF8u5K1J+O+eMdCxRj+qLlhv3fisxMBpCK1Onbb9SjN0xyyGzckdzBeb+9GS3bmAL2tYSx83NIrksjeInbzno65xu7rSl9tatMKVPcyKLeAc1JluOLptV/kSkDRG1+G9e4/8Ru/qFr2HyOr5YS4YkvwaW8lpNs30xkVRCfhjFZzYzWg8HRtGSoqRN6zWYmtY/xKYYYN/NGDGNuwPf2NUNn6pa1ELX0pg5SZMewgDqGmQ1h4jEv3XEqr1JKe4UfOH/vPORVBErOkcJKS9JxWQsDg=
